#!/bin/tcsh

set RUNNING_DIRECTORY=${1}
cd ${RUNNING_DIRECTORY}
setenv CONTINUOUS_DURATION ${2}
setenv CONTINUOUS_INTERVAL ${3}
foreach project (`cat continuous_projects | grep -v '#'`)
    touch ci_${project}
    ${RUNNING_DIRECTORY}/run_automated_tests ${RUNNING_DIRECTORY}/projects Continuous ${RUNNING_DIRECTORY} ${project} &
end
